# Generated by Django 4.2.3 on 2023-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.CharField(max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Telegram chat id')),
                ('privat_url', models.CharField(default='none', max_length=56, verbose_name='Приватная ссылка пользователя')),
                ('public_url', models.CharField(default='none', max_length=56, verbose_name='Публичная ссылка пользователя')),
                ('last_callback', models.CharField(default='none', max_length=56, verbose_name='Последний callback')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
