# Generated by Django 4.2.3 on 2023-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='last_id',
            field=models.CharField(default='none', max_length=56, verbose_name='Последний callback ID'),
        ),
    ]
